# Generated by Django 5.2.3 on 2025-06-26 17:25

import colorfield.fields
import deliveries.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('label', models.CharField(blank=True, default='', max_length=50, verbose_name='label')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'Additional Service',
                'verbose_name_plural': 'Additional Services',
            },
        ),
        migrations.CreateModel(
            name='PackingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('label', models.CharField(blank=True, default='', max_length=50, verbose_name='label')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'Packing Type',
                'verbose_name_plural': 'Packing Types',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('label', models.CharField(blank=True, default='', max_length=50, verbose_name='label')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order of the status. Lower number means higher priority', verbose_name='order')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, help_text='Color code in hex format', image_field=None, max_length=25, null=True, samples=None, verbose_name='color')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('label', models.CharField(blank=True, default='', max_length=50, verbose_name='label')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.TextField(verbose_name='from address')),
                ('to_address', models.TextField(verbose_name='to address')),
                ('distance', models.PositiveIntegerField(help_text='in km', verbose_name='distance')),
                ('from_datetime', models.DateTimeField(verbose_name='from datetime')),
                ('to_datetime', models.DateTimeField(verbose_name='to datetime')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('additional_services', models.ManyToManyField(blank=True, to='deliveries.additionalservice', verbose_name='additional services')),
                ('packing_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveries.packingtype', verbose_name='packing type')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveries.status', verbose_name='status')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveries.transport', verbose_name='transport')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='DeliveryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='File related to the delivery', upload_to='upload/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), deliveries.validators.FileSizeValidator(5)], verbose_name='file')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.delivery', verbose_name='delivery')),
            ],
            options={
                'verbose_name': 'Delivery File',
                'verbose_name_plural': 'Delivery Files',
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.delivery', verbose_name='delivery')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.status', verbose_name='status')),
            ],
            options={
                'verbose_name': 'Delivery Status History',
                'verbose_name_plural': 'Delivery Status Histories',
            },
        ),
    ]
